# This is a generated file. Not intended for manual editing.
services:
  testcdci:
    build:
      context: "/Users/azimzada.mahammad/work/webconsole/TestCdCi"
      dockerfile: "TestCdCi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/TestCdCi.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/TestCdCi.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "testcdci:dev"
    ports: []
    volumes:
    - "/Users/azimzada.mahammad/work/webconsole/TestCdCi/TestCdCi:/app:rw"
    - "/Users/azimzada.mahammad/work/webconsole/TestCdCi:/src:rw"
    - "/Users/azimzada.mahammad/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
